export const standings2022 = [
  {
    name: "Benton",
    rating: 1086,
  },
  {
    name: "Peter",
    rating: 1067,
  },
  {
    name: "Jimmy",
    rating: 1020,
  },
  {
    name: "Greg",
    rating: 1017,
  },
  {
    name: "Rob",
    rating: 971,
  },
  {
    name: "Samir",
    rating: 966,
  },
  {
    name: "Lane",
    rating: 958,
  },
  {
    name: "Alex",
    rating: 933,
  }
]

export const standings2023 = [
  {
    name: "Benton",
    rating: 1056,
  },
  {
    name: "Peter",
    rating: 1031,
  },
  {
    name: "Jimmy",
    rating: 1016,
  },
  {
    name: "Greg",
    rating: 1008,
  },
  {
    name: "Rob",
    rating: 978,
  },
  {
    name: "Alex",
    rating: 953,
  },
  {
    name: "Lane",
    rating: 936,
  }
]

export const tourney2023 = [
  {
    "Course": "Acorn Park",
    "Layout": "Short Tees -> Long Baskets.",
    "Par": "57",
    "Date": "2023-09-23 1600",
    "Players": [
        {
          "holes": [
            "3",
            "3",
            "4",
            "3",
            "3",
            "3",
            "4",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "4",
            "3",
            "3",
            "3"
          ],
          "player": "Par",
          "plusMinus": "",
          "total": "57"
        },
        {
            "player": "Peter",
            "total": "55",
            "plusMinus": "-2",
            "holes": [
                "3",
                "4",
                "3",
                "3",
                "3",
                "2",
                "4",
                "3",
                "2",
                "3",
                "3",
                "2",
                "4",
                "2",
                "4",
                "3",
                "3",
                "4"
            ]
        },
        {
            "player": "Rob Renkor",
            "total": "65",
            "plusMinus": "8",
            "holes": [
                "2",
                "4",
                "4",
                "5",
                "3",
                "3",
                "5",
                "3",
                "3",
                "3",
                "2",
                "3",
                "3",
                "5",
                "5",
                "4",
                "4",
                "4"
            ]
        },
        {
            "player": "Lane ",
            "total": "72",
            "plusMinus": "15",
            "holes": [
                "3",
                "5",
                "5",
                "4",
                "4",
                "4",
                "6",
                "3",
                "3",
                "4",
                "4",
                "3",
                "3",
                "3",
                "5",
                "5",
                "4",
                "4"
            ]
        },
        {
            "player": "Benton",
            "total": "54",
            "plusMinus": "-3",
            "holes": [
                "2",
                "2",
                "4",
                "4",
                "3",
                "2",
                "5",
                "3",
                "2",
                "2",
                "2",
                "3",
                "3",
                "3",
                "4",
                "3",
                "3",
                "4"
            ]
        },
        {
            "player": "Greg L",
            "total": "57",
            "plusMinus": "0",
            "holes": [
                "2",
                "3",
                "3",
                "4",
                "3",
                "3",
                "4",
                "3",
                "2",
                "3",
                "3",
                "3",
                "3",
                "4",
                "5",
                "2",
                "3",
                "4"
            ]
        },
        {
            "player": "Alex Oelke",
            "total": "69",
            "plusMinus": "12",
            "holes": [
                "4",
                "4",
                "4",
                "4",
                "4",
                "4",
                "5",
                "3",
                "4",
                "2",
                "4",
                "4",
                "5",
                "4",
                "4",
                "3",
                "3",
                "4"
            ]
        },
        {
            "player": "Jimmy",
            "total": "64",
            "plusMinus": "7",
            "holes": [
                "3",
                "4",
                "5",
                "5",
                "3",
                "4",
                "6",
                "3",
                "3",
                "3",
                "3",
                "3",
                "3",
                "2",
                "5",
                "2",
                "3",
                "4"
            ]
        }
    ]
  },
  {
    "Course": "Wildwood 9 Disc Golf Course",
    "Layout": "18 Holes (2 Rounds)",
    "Par": "56",
    "Date": "2023-09-23 1900",
    "Players": [
        {
          "holes": [
            "3",
            "3",
            "3",
            "3",
            "3",
            "4",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "3",
            "4",
            "3",
            "3",
            "3"
          ],
          "player": "Par",
          "plusMinus": "",
          "total": "56"
        },
        {
            "player": "Peter",
            "total": "64",
            "plusMinus": "8",
            "holes": [
                "3",
                "2",
                "4",
                "4",
                "3",
                "4",
                "5",
                "3",
                "6",
                "3",
                "3",
                "4",
                "3",
                "3",
                "5",
                "4",
                "3",
                "2"
            ]
        },
        {
            "player": "Rob Renkor",
            "total": "71",
            "plusMinus": "15",
            "holes": [
                "3",
                "3",
                "4",
                "4",
                "3",
                "6",
                "4",
                "3",
                "4",
                "4",
                "5",
                "5",
                "4",
                "4",
                "5",
                "4",
                "3",
                "3"
            ]
        },
        {
            "player": "Lane ",
            "total": "78",
            "plusMinus": "22",
            "holes": [
                "4",
                "3",
                "4",
                "5",
                "2",
                "7",
                "4",
                "5",
                "4",
                "3",
                "5",
                "4",
                "5",
                "4",
                "7",
                "4",
                "4",
                "4"
            ]
        },
        {
            "player": "Benton",
            "total": "61",
            "plusMinus": "5",
            "holes": [
                "3",
                "3",
                "4",
                "3",
                "2",
                "4",
                "3",
                "3",
                "4",
                "4",
                "3",
                "3",
                "3",
                "3",
                "5",
                "3",
                "4",
                "4"
            ]
        },
        {
            "player": "Greg L",
            "total": "68",
            "plusMinus": "12",
            "holes": [
                "2",
                "4",
                "4",
                "4",
                "3",
                "7",
                "3",
                "3",
                "3",
                "4",
                "3",
                "4",
                "4",
                "2",
                "6",
                "4",
                "3",
                "5"
            ]
        },
        {
            "player": "Alex Oelke",
            "total": "76",
            "plusMinus": "20",
            "holes": [
                "6",
                "4",
                "4",
                "4",
                "3",
                "7",
                "3",
                "3",
                "5",
                "5",
                "4",
                "4",
                "3",
                "4",
                "5",
                "4",
                "3",
                "5"
            ]
        }
    ]
  }
]

export const tourney2022 = [
  {
    "Course": "Moir Park",
    "Date": "2022-10-16 1100",
    "Layout": "Twice Around",
    "Par": "54",
    "Players": [
      {
        "holes": [
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3"
        ],
        "player": "Par",
        "plusMinus": "",
        "total": "54"
      },
      {
        "holes": [
          "3",
          "2",
          "3",
          "3",
          "3",
          "3",
          "3",
          "2",
          "3",
          "3",
          "3",
          "4",
          "3",
          "2",
          "4",
          "3",
          "2",
          "3"
        ],
        "player": "Benton",
        "plusMinus": "-2",
        "total": "52"
      },
      {
        "holes": [
          "4",
          "3",
          "4",
          "3",
          "3",
          "3",
          "3",
          "4",
          "4",
          "3",
          "3",
          "2",
          "3",
          "3",
          "3",
          "3",
          "3",
          "4"
        ],
        "player": "Peter",
        "plusMinus": "4",
        "total": "58"
      },
      {
        "holes": [
          "4",
          "4",
          "2",
          "4",
          "3",
          "3",
          "4",
          "2",
          "4",
          "4",
          "2",
          "4",
          "3",
          "2",
          "4",
          "3",
          "4",
          "4"
        ],
        "player": "Jimmy",
        "plusMinus": "6",
        "total": "60"
      },
      {
        "holes": [
          "4",
          "2",
          "2",
          "3",
          "3",
          "2",
          "3",
          "4",
          "3",
          "4",
          "3",
          "4",
          "5",
          "4",
          "2",
          "3",
          "3",
          "3"
        ],
        "player": "Alex",
        "plusMinus": "3",
        "total": "57"
      },
      {
        "holes": [
          "5",
          "3",
          "3",
          "4",
          "3",
          "3",
          "4",
          "3",
          "2",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3"
        ],
        "player": "Greg L",
        "plusMinus": "3",
        "total": "57"
      },
      {
        "holes": [
          "3",
          "3",
          "2",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "2",
          "4",
          "4",
          "3",
          "4",
          "4",
          "3",
          "4"
        ],
        "player": "Rob",
        "plusMinus": "3",
        "total": "57"
      },
      {
        "holes": [
          "3",
          "2",
          "3",
          "3",
          "2",
          "2",
          "2",
          "3",
          "3",
          "3",
          "2",
          "3",
          "3",
          "3",
          "3",
          "5",
          "2",
          "2"
        ],
        "player": "Samir",
        "plusMinus": "-5",
        "total": "49"
      },
      {
        "holes": [
          "4",
          "3",
          "3",
          "4",
          "3",
          "4",
          "3",
          "3",
          "3",
          "4",
          "3",
          "4",
          "5",
          "3",
          "3",
          "5",
          "3",
          "4"
        ],
        "player": "Lane",
        "plusMinus": "10",
        "total": "64"
      },
    ],
    "dateAdded": "Tue Aug 15 2023 16:10:56 GMT-0500 (Central Daylight Time)",
    "id": 99949195
  },
  {
    "Course": "Lakewood Hills",
    "Date": "2022-10-16 1400",
    "Layout": "Short Tees",
    "Par": "57",
    "Players": [
      {
        "holes": [
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "4",
          "4",
          "3",
          "4",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3"
        ],
        "player": "Par",
        "plusMinus": "",
        "total": "57"
      },
      {
        "holes": [
          "4",
          "3",
          "3",
          "2",
          "3",
          "3",
          "5",
          "2",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "5",
          "4",
          "3",
          "3"
        ],
        "player": "Benton",
        "plusMinus": "1",
        "total": "58"
      },
      {
        "holes": [
          "3",
          "4",
          "3",
          "3",
          "3",
          "2",
          "4",
          "3",
          "3",
          "4",
          "3",
          "2",
          "3",
          "3",
          "5",
          "6",
          "3",
          "3"
        ],
        "player": "Greg",
        "plusMinus": "3",
        "total": "60"
      },
      {
        "holes": [
          "5",
          "3",
          "4",
          "5",
          "4",
          "4",
          "7",
          "3",
          "3",
          "6",
          "4",
          "4",
          "4",
          "3",
          "4",
          "6",
          "5",
          "4"
        ],
        "player": "Rob Renkor",
        "plusMinus": "21",
        "total": "78"
      },
      {
        "holes": [
          "4",
          "3",
          "3",
          "3",
          "4",
          "4",
          "4",
          "4",
          "3",
          "3",
          "3",
          "3",
          "3",
          "3",
          "4",
          "5",
          "4",
          "3"
        ],
        "player": "Samir",
        "plusMinus": "7",
        "total": "64"
      },
      {
        "holes": [
          "4",
          "3",
          "4",
          "3",
          "3",
          "4",
          "5",
          "2",
          "4",
          "3",
          "4",
          "3",
          "3",
          "3",
          "4",
          "4",
          "5",
          "3"
        ],
        "player": "Peter",
        "plusMinus": "7",
        "total": "64"
      },
      {
        "holes": [
          "4",
          "3",
          "4",
          "4",
          "3",
          "3",
          "5",
          "3",
          "3",
          "3",
          "4",
          "4",
          "3",
          "3",
          "4",
          "4",
          "10",
          "5"
        ],
        "player": "Jimmy",
        "plusMinus": "15",
        "total": "72"
      },
      {
        "holes": [
          "5",
          "4",
          "3",
          "3",
          "4",
          "6",
          "6",
          "4",
          "3",
          "3",
          "4",
          "3",
          "4",
          "4",
          "5",
          "6",
          "4",
          "4"
        ],
        "player": "Alex",
        "plusMinus": "18",
        "total": "75"
      },
      {
        "holes": [
          "4",
          "4",
          "6",
          "3",
          "3",
          "3",
          "5",
          "4",
          "4",
          "4",
          "5",
          "3",
          "4",
          "5",
          "6",
          "6",
          "4",
          "4"
        ],
        "player": "Lane ",
        "plusMinus": "20",
        "total": "77"
      }
    ],
    "dateAdded": "Tue Aug 15 2023 16:11:06 GMT-0500 (Central Daylight Time)",
    "id": 46217508
  }
]

export const stats2022 = {
  numRounds: 26,
  hardest: 'Lochness (5.31)',
  most: 'Basset Creek Park (3)',
  avgPlayer: 'Greg (1017)',
  winner: 'Benton (-1)',
  rest: 'Samir (+2), Greg (+6), Peter (+11), Jimmy (+21), Alex (+21), Rob (+24), Lane (+30)'
}

export const stats2023 = {
  numRounds: 22,
  hardest: 'Elm Creek Park Reserve - Main / Kaposia Park 27 Hole (Full Course) (4.5)',
  most: 'Basset Creek Park (3)',
  avgPlayer: 'Greg (1008)',
  winner: 'Benton (+2)',
  rest: 'Peter (+6), Greg (+12), Rob (+23), Alex (+32), Lane (+37), Jimmy (IL)'
}